name: main
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # gives standard-version access to all previous commits
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: build
        run: |
          make code/build-cross
