name: release
on:
  workflow_dispatch:
    inputs:
      extra-release-args:
        required: false
        default: ""
        description: "Extra args to pass to standard-version"
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # gives standard-version access to all previous commits
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: build
        run: |
          make code/build-cross
      - name: generate tag and release body
        run: |
          git config user.name Github Releaser
          git config user.email alexandre.ledit@airnity.com
          npx standard-version -i RELEASE_BODY.md -t "" --skip.commit --skip.tag ${{ github.event.inputs.extra-release-args }}
          npx standard-version -t "" ${{ github.event.inputs.extra-release-args }}
      - name: publish tag
        id: publish_tag
        run: |
          git push --follow-tags
          echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)
      - name: create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body_path: RELEASE_BODY.md

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./dist/bin/darwin-arm64/router-sidecar
          asset_name: darwin-arm64/router-sidecar
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./dist/bin/linux-amd64/router-sidecar
          asset_name: linux-amd64/router-sidecar
          asset_content_type: application/octet-stream
